fast_food=['Burger king', "Wendy's", "Macdonald's", "Popeyes", "Church's Chicken", "Arby's", "A&W"]
print("1. Fast Food:",fast_food)
fast_food.insert(0, 'Applebees')
print("2. Fast Food:",fast_food)
fast_food.remove('Popeyes')
print("3. Fast Food:",fast_food)
print("There's",len(fast_food),"fast food places near us")
fast_food.append('Five Guys')
print("4. Fast Food:",fast_food)
print("Sorted():",sorted(fast_food))
print("5. Fast Food:",fast_food)
fast_food.sort()
print("6. Fast Food:",fast_food)
print("Popped 1.",fast_food.pop())
print("Popped 2.",fast_food.pop())
print("Popped 3.",fast_food.pop())
print("7. Fast Food:",fast_food)
fast_food.reverse()
print("8. Fast Food:",fast_food)