guests=['Michelle', 'Chad', 'Chris']
print("Hey I found a bigger table",guests)
guests.insert(0, 'Joseph')
guests.insert(1, 'MIllah')
guests.insert(2, 'Katy')
print('Please come over for dinner',guests[0])
print('Please come over for dinner',guests[1])
print('Please come over for dinner',guests[2])
print('Please come over for dinner',guests[3])
print('Please come over for dinner',guests[4])
print('Please come over for dinner',guests[5])
